import type { Agent, ActivityEvent, Service } from "@/types";

const wallet = (suffix: string) => `0x${suffix}`;

export const AGENTS: Agent[] = [
  {
    id: "payment-agent",
    name: "PAYMENT AGENT",
    type: "SETTLEMENT",
    purpose: "Authorize, route and settle programmable payments for other agents.",
    status: "ONLINE",
    capabilities: ["PAY", "VERIFY", "SETTLE", "DISCOVER"],
    balance: 128.4,
    spendingPerTask: 50,
    tasksCompleted: 1284,
    lastAction: "Settled 0.001 USDC → Market Data API",
    wallet: wallet("A1F2...9C4D"),
    policy: {
      maxDailySpend: 500,
      maxPerTransaction: 50,
      network: "ARC",
      asset: "USDC",
      riskMode: "BALANCED",
      sessionMinutes: 240,
      confirmUnknownRecipient: true,
      confirmContractInteraction: true,
      confirmAboveLimit: true,
      allowedServices: ["market-data-api", "ai-inference", "data-api"],
      allowedContracts: ["ARC:USDC"],
    },
    tasks: [
      { id: "T-8821", name: "Settle nanopayment batch", status: "COMPLETED", cost: 0.014, at: "10:42:35" },
      { id: "T-8822", name: "Authorize inference call", status: "COMPLETED", cost: 0.004, at: "10:41:02" },
      { id: "T-8823", name: "Verify settlement receipt", status: "RUNNING", cost: 0, at: "10:43:10" },
    ],
    payments: [
      { id: "PAY-4471", to: "Market Data API", amount: 0.001, status: "SETTLED", at: "10:42:35" },
      { id: "PAY-4470", to: "AI Inference", amount: 0.004, status: "SETTLED", at: "10:41:02" },
      { id: "PAY-4469", to: "Web Search", amount: 0.0008, status: "AUTHORIZED", at: "10:39:55" },
    ],
    logs: [
      { at: "10:42:31", channel: "AGENT", message: "Discovery request issued for category=market-data" },
      { at: "10:42:32", channel: "SERVICE", message: "Market Data API responded 402 PAYMENT REQUIRED" },
      { at: "10:42:33", channel: "PAYMENT", message: "0.001 USDC authorized under per-task policy" },
      { at: "10:42:35", channel: "SETTLEMENT", message: "Confirmed on ARC (simulated)" },
    ],
    origin: "DEMO",
  },
  {
    id: "research-agent",
    name: "RESEARCH AGENT",
    type: "KNOWLEDGE",
    purpose: "Search, read and synthesize external sources into structured briefs.",
    status: "BUSY",
    capabilities: ["SEARCH", "READ", "SUMMARIZE", "PAY"],
    balance: 42.15,
    spendingPerTask: 5,
    tasksCompleted: 611,
    lastAction: "Purchased 12 web-search calls",
    wallet: wallet("77B3...1E08"),
    policy: {
      maxDailySpend: 100,
      maxPerTransaction: 5,
      network: "ARC",
      asset: "USDC",
      riskMode: "SAFE",
      sessionMinutes: 120,
      confirmUnknownRecipient: true,
      confirmContractInteraction: true,
      confirmAboveLimit: true,
      allowedServices: ["web-search", "content"],
      allowedContracts: ["ARC:USDC"],
    },
    tasks: [
      { id: "T-6610", name: "Compile agentic payments brief", status: "RUNNING", cost: 0.031, at: "10:40:12" },
      { id: "T-6609", name: "Source verification pass", status: "COMPLETED", cost: 0.012, at: "10:22:04" },
    ],
    payments: [{ id: "PAY-3310", to: "Web Search", amount: 0.012, status: "SETTLED", at: "10:22:04" }],
    logs: [
      { at: "10:40:12", channel: "AGENT", message: "Task accepted: compile brief" },
      { at: "10:40:18", channel: "PAYMENT", message: "0.012 USDC authorized for web-search" },
    ],
    origin: "DEMO",
  },
  {
    id: "data-agent",
    name: "DATA AGENT",
    type: "INGESTION",
    purpose: "Pull, normalize and stream structured datasets to downstream agents.",
    status: "ONLINE",
    capabilities: ["FETCH", "NORMALIZE", "STREAM", "PAY"],
    balance: 88.9,
    spendingPerTask: 10,
    tasksCompleted: 2940,
    lastAction: "Requested Market Data API",
    wallet: wallet("C4D9...77AA"),
    policy: {
      maxDailySpend: 250,
      maxPerTransaction: 10,
      network: "ARC",
      asset: "USDC",
      riskMode: "BALANCED",
      sessionMinutes: 480,
      confirmUnknownRecipient: true,
      confirmContractInteraction: false,
      confirmAboveLimit: true,
      allowedServices: ["market-data-api", "data-api", "oracle"],
      allowedContracts: ["ARC:USDC"],
    },
    tasks: [{ id: "T-2201", name: "Stream orderbook snapshots", status: "RUNNING", cost: 0.09, at: "10:43:01" }],
    payments: [{ id: "PAY-9902", to: "Market Data API", amount: 0.001, status: "PENDING", at: "10:43:02" }],
    logs: [{ at: "10:43:01", channel: "AGENT", message: "Opened streaming session with market-data-api" }],
    origin: "DEMO",
  },
  {
    id: "api-agent",
    name: "API AGENT",
    type: "INTEGRATION",
    purpose: "Negotiate machine-readable pricing and call paid endpoints on demand.",
    status: "IDLE",
    capabilities: ["CALL", "NEGOTIATE", "RETRY", "PAY"],
    balance: 19.75,
    spendingPerTask: 2,
    tasksCompleted: 421,
    lastAction: "Idle — awaiting task",
    wallet: wallet("5E11...0B62"),
    policy: {
      maxDailySpend: 50,
      maxPerTransaction: 2,
      network: "ARC",
      asset: "USDC",
      riskMode: "SAFE",
      sessionMinutes: 60,
      confirmUnknownRecipient: true,
      confirmContractInteraction: true,
      confirmAboveLimit: true,
      allowedServices: ["data-api", "storage"],
      allowedContracts: ["ARC:USDC"],
    },
    tasks: [],
    payments: [],
    logs: [{ at: "09:58:00", channel: "AGENT", message: "Session expired — awaiting re-authorization" }],
    origin: "DEMO",
  },
  {
    id: "trading-agent",
    name: "TRADING AGENT",
    type: "EXECUTION",
    purpose: "Evaluate market data feeds and execute policy-bounded strategies.",
    status: "ONLINE",
    capabilities: ["ANALYZE", "QUOTE", "EXECUTE", "PAY"],
    balance: 310.0,
    spendingPerTask: 25,
    tasksCompleted: 1502,
    lastAction: "Evaluated 42 signals",
    wallet: wallet("9AB0...FF31"),
    policy: {
      maxDailySpend: 1000,
      maxPerTransaction: 25,
      network: "ARC",
      asset: "USDC",
      riskMode: "AUTONOMOUS",
      sessionMinutes: 720,
      confirmUnknownRecipient: true,
      confirmContractInteraction: true,
      confirmAboveLimit: true,
      allowedServices: ["market-data-api", "oracle", "compute"],
      allowedContracts: ["ARC:USDC"],
    },
    tasks: [{ id: "T-7710", name: "Signal sweep", status: "COMPLETED", cost: 0.22, at: "10:38:40" }],
    payments: [{ id: "PAY-7701", to: "Oracle Feed", amount: 0.05, status: "SETTLED", at: "10:38:41" }],
    logs: [{ at: "10:38:40", channel: "POLICY", message: "Autonomous mode active — per-tx ceiling 25 USDC" }],
    origin: "DEMO",
  },
  {
    id: "compute-agent",
    name: "COMPUTE AGENT",
    type: "RUNTIME",
    purpose: "Rent ephemeral compute and pay per second of execution.",
    status: "OFFLINE",
    capabilities: ["PROVISION", "RUN", "TEARDOWN", "PAY"],
    balance: 0,
    spendingPerTask: 15,
    tasksCompleted: 88,
    lastAction: "Runtime terminated",
    wallet: wallet("13CC...48E7"),
    policy: {
      maxDailySpend: 120,
      maxPerTransaction: 15,
      network: "ARC",
      asset: "USDC",
      riskMode: "BALANCED",
      sessionMinutes: 30,
      confirmUnknownRecipient: true,
      confirmContractInteraction: true,
      confirmAboveLimit: true,
      allowedServices: ["compute", "storage"],
      allowedContracts: ["ARC:USDC"],
    },
    tasks: [],
    payments: [],
    logs: [{ at: "08:12:00", channel: "AGENT", message: "Runtime terminated — balance depleted" }],
    origin: "DEMO",
  },
];

export const SERVICES: Service[] = [
  {
    id: "market-data-api",
    name: "Market Data API",
    category: "MARKET DATA",
    price: 0.001,
    unit: "request",
    method: "USDC",
    network: "ARC",
    status: "AVAILABLE",
    provider: "arcfeed.demo",
    responseTimeMs: 84,
    description:
      "Sub-cent priced market snapshots designed for agent consumption. Returns a 402 Payment Required challenge before releasing the payload.",
    endpoint: "GET /v1/market/snapshot?symbol=ETHUSD",
    capabilities: ["SNAPSHOT", "OHLCV", "ORDERBOOK"],
    sampleResponse: `{
  "symbol": "ETHUSD",
  "price": "—",
  "source": "demo-fixture",
  "mode": "DEMO"
}`,
    compatibility: ["PAYMENT AGENT", "DATA AGENT", "TRADING AGENT"],
    origin: "DEMO",
  },
  {
    id: "ai-inference",
    name: "AI Inference",
    category: "INFERENCE",
    price: 0.004,
    unit: "call",
    method: "USDC",
    network: "ARC",
    status: "AVAILABLE",
    provider: "inference.demo",
    responseTimeMs: 640,
    description: "Metered model inference billed per call with machine-readable pricing headers.",
    endpoint: "POST /v1/infer",
    capabilities: ["COMPLETION", "EMBEDDING", "RERANK"],
    sampleResponse: `{ "output": "—", "tokens": 0, "mode": "DEMO" }`,
    compatibility: ["RESEARCH AGENT", "API AGENT"],
    origin: "DEMO",
  },
  {
    id: "web-search",
    name: "Web Search",
    category: "DISCOVERY",
    price: 0.0008,
    unit: "query",
    method: "USDC",
    network: "ARC",
    status: "AVAILABLE",
    provider: "search.demo",
    responseTimeMs: 210,
    description: "Agent-oriented search index with per-query nanopayment settlement.",
    endpoint: "GET /v1/search?q=",
    capabilities: ["QUERY", "RANK", "CITE"],
    sampleResponse: `{ "results": [], "mode": "DEMO" }`,
    compatibility: ["RESEARCH AGENT"],
    origin: "DEMO",
  },
  {
    id: "compute",
    name: "Compute Runtime",
    category: "COMPUTE",
    price: 0.012,
    unit: "second",
    method: "USDC",
    network: "ARC",
    status: "DEGRADED",
    provider: "runtime.demo",
    responseTimeMs: 1200,
    description: "Ephemeral sandboxed runtime rented by the second, torn down on settlement failure.",
    endpoint: "POST /v1/runtime/session",
    capabilities: ["PROVISION", "EXEC", "TEARDOWN"],
    sampleResponse: `{ "session": "—", "mode": "DEMO" }`,
    compatibility: ["COMPUTE AGENT"],
    origin: "DEMO",
  },
  {
    id: "storage",
    name: "Object Storage",
    category: "STORAGE",
    price: 0.0002,
    unit: "MB",
    method: "USDC",
    network: "ARC",
    status: "AVAILABLE",
    provider: "vault.demo",
    responseTimeMs: 150,
    description: "Durable object storage that preserves original file bytes and MIME types.",
    endpoint: "PUT /v1/objects/:key",
    capabilities: ["PUT", "GET", "SIGN"],
    sampleResponse: `{ "key": "—", "mode": "DEMO" }`,
    compatibility: ["API AGENT", "COMPUTE AGENT"],
    origin: "DEMO",
  },
  {
    id: "data-api",
    name: "Data API",
    category: "DATA",
    price: 0.0015,
    unit: "request",
    method: "USDC",
    network: "ARC",
    status: "AVAILABLE",
    provider: "datagrid.demo",
    responseTimeMs: 120,
    description: "Structured dataset access with row-level metering.",
    endpoint: "GET /v1/datasets/:id/rows",
    capabilities: ["QUERY", "STREAM", "SCHEMA"],
    sampleResponse: `{ "rows": [], "mode": "DEMO" }`,
    compatibility: ["DATA AGENT", "API AGENT"],
    origin: "DEMO",
  },
  {
    id: "content",
    name: "Content Engine",
    category: "CONTENT",
    price: 0.006,
    unit: "document",
    method: "USDC",
    network: "ARC",
    status: "AVAILABLE",
    provider: "compose.demo",
    responseTimeMs: 880,
    description: "Document generation billed per artifact produced.",
    endpoint: "POST /v1/content/compose",
    capabilities: ["COMPOSE", "FORMAT", "EXPORT"],
    sampleResponse: `{ "document": "—", "mode": "DEMO" }`,
    compatibility: ["RESEARCH AGENT"],
    origin: "DEMO",
  },
  {
    id: "oracle",
    name: "Oracle Feed",
    category: "ORACLE",
    price: 0.05,
    unit: "attestation",
    method: "USDC",
    network: "ARC",
    status: "AVAILABLE",
    provider: "oracle.demo",
    responseTimeMs: 320,
    description: "Signed attestations for off-chain values consumed by settlement logic.",
    endpoint: "GET /v1/oracle/attest",
    capabilities: ["ATTEST", "SIGN", "VERIFY"],
    sampleResponse: `{ "attestation": "—", "mode": "DEMO" }`,
    compatibility: ["TRADING AGENT", "PAYMENT AGENT"],
    origin: "DEMO",
  },
];

export const getAgent = (id: string) => AGENTS.find((a) => a.id === id);
export const getService = (id: string) => SERVICES.find((s) => s.id === id);

const ACTORS = AGENTS.filter((a) => a.status !== "OFFLINE").map((a) => a.name);
const ACTIONS: Array<{ action: string; target: string; amount?: number }> = [
  { action: "requested", target: "Market Data API", amount: 0.001 },
  { action: "paid", target: "AI Inference", amount: 0.004 },
  { action: "settled", target: "ARC" },
  { action: "authorized", target: "Web Search", amount: 0.0008 },
  { action: "discovered", target: "Oracle Feed" },
  { action: "verified", target: "Settlement receipt" },
  { action: "executed", target: "Data API", amount: 0.0015 },
];

export function makeActivityEvent(seed = Date.now()): ActivityEvent {
  const a = ACTIONS[seed % ACTIONS.length]!;
  const actor = ACTORS[(seed >> 3) % ACTORS.length]!;
  const now = new Date();
  return {
    id: `${seed}-${Math.floor(Math.random() * 1e6)}`,
    time: now.toTimeString().slice(0, 8),
    actor,
    action: a.action,
    target: a.target,
    amount: a.amount,
    network: "ARC",
  };
}

export const DASHBOARD_SERIES = {
  agentActivity: [12, 18, 15, 26, 22, 34, 30, 41, 38, 47, 44, 52],
  paymentVolume: [4, 9, 7, 14, 11, 19, 17, 24, 21, 29, 26, 33],
  serviceUsage: [
    { label: "MARKET DATA", value: 42 },
    { label: "INFERENCE", value: 28 },
    { label: "SEARCH", value: 15 },
    { label: "STORAGE", value: 9 },
    { label: "COMPUTE", value: 6 },
  ],
  txFrequency: [3, 6, 4, 9, 7, 12, 10, 16, 13, 18, 15, 21],
};
